Repository fthomas/refined, pull requests merged in 2020-09, with the labels that each got.

#841 Allow Int and Double literals as universal arguments
  modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/internal/WitnessAs.scala
  modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/numeric.scala
  modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/internal/WitnessAs.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/NumericValidateSpec.scala
Labels: enhancement

#822 Update pureconfig-core, ... to 0.14.0
  build.sbt
  modules/pureconfig/shared/src/main/scala/eu/timepit/refined/pureconfig/package.scala
Labels: dependency-update

#844 Update Scaladoc of the numeric module
  modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/numeric.scala
  modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/numeric.scala
Labels: documentation

#845 Prepare tests for deprecating support of Nat
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/BooleanInferenceSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/BooleanValidateSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/CollectionInferenceSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/CollectionValidateSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/GenericInferenceSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/GenericValidateSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/MaxSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/MinSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/NumericInferenceSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/NumericValidateSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/RefineMSpec.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/api/RefTypeSpec.scala
Labels: testing

#846 Add NonEmptyFiniteString[N].truncateNes
  modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/types/string.scala
  modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/types/string.scala
  modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/types/StringTypesSpec.scala
Labels: enhancement

#847 Do not use Nat in scalacheck tests
  modules/scalacheck/shared/src/test/scala-3.0-/eu/timepit/refined/scalacheck/CollectionArbitrarySpec.scala
  modules/scalacheck/shared/src/test/scala-3.0-/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
Labels: testing

#849 Update scalafmt-core to 2.7.3
  .scalafmt.conf
Labels: dependency-update
