Repository fthomas/refined, pull requests merged in 2020-10, with the labels that each got.

#851 Don't use partial function in MiMa setting
  build.sbt
  latestVersion.sbt
Labels: build

#852 Update sbt to 1.4.0
  project/build.properties
Labels: dependency-update

#853 Update scalafmt-core to 2.7.4
  .scalafmt.conf
Labels: dependency-update

#854 Add take method to NonEmptyList and NonEmptyVector
  modules/cats/shared/src/main/scala/eu/timepit/refined/cats/syntax.scala
  modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SyntaxSpec.scala
Labels: enhancement

#856 Update scalafmt-core to 2.7.5
  .scalafmt.conf
  modules/cats/shared/src/main/scala/eu/timepit/refined/cats/syntax.scala
  modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SyntaxSpec.scala
Labels: dependency-update

#857 Update sbt-dotty to 0.4.3
  project/plugins.sbt
Labels: dependency-update

#855 Update sbt-scalajs, scalajs-compiler, ... to 1.3.0
  project/plugins.sbt
Labels: dependency-update

#858 Update sbt-dotty to 0.4.4
  project/plugins.sbt
Labels: dependency-update

#859 Update sbt-mima-plugin to 0.8.1
  project/plugins.sbt
Labels: dependency-update

#860 Update sbt to 1.4.1
  project/build.properties
Labels: dependency-update

#861 Update sbt-dotty to 0.4.5
  project/plugins.sbt
Labels: dependency-update

#862 Update scalacheck, scalacheck_2.13 to 1.15.0
  build.sbt
Labels: dependency-update
